#	***install openvpn
# HISTORY
#	171282 - created, not yet tested, but should work
#
#
echo "Run this script as ROOT!! -"
echo "@@@copy /etc/openvpn/server directory from backup if present"
echo "if necessary copy passwords out of password manager, if present"
read -n1 -r -p "Press space to continue..." key
echo ""
#
pacman -S openvpn
#
systemctl enable openvpn-server@server.service
systemctl start openvpn-server@server.service
systemctl status openvpn-server@server.service
#
# 
# enable IPv4 packet forwarding
cat <<EOFIP4F >/etc/sysctl.d/99-sysctl.conf
net.ipv4.ip_forward=1
EOFIP4F

echo "OpenVPN runs on TCP port 443 (https) because this port is never blocked on public networks"
#
cat <<EOFIPTABLES >/etc/iptables/iptables.rules
# Generated by iptables-save v1.4.21 on Sun Feb 22 22:17:21 2015
*filter
:INPUT ACCEPT [77970:105347363]
:FORWARD ACCEPT [323:19349]
:OUTPUT ACCEPT [39152:2541354]
-A FORWARD -i eth0 -o tun0 -j ACCEPT
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
COMMIT
# Completed on Sun Feb 22 22:17:21 2015
# Generated by iptables-save v1.4.21 on Sun Feb 22 22:17:21 2015
*nat
:PREROUTING ACCEPT [72:4721]
:INPUT ACCEPT [3:681]
:OUTPUT ACCEPT [4:304]
:POSTROUTING ACCEPT [4:304]
-A INPUT -i eth0 -p tcp -m tcp --dport 443 -j ACCEPT
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j SNAT --to-source ip-of-server
COMMIT
# Completed on Sun Feb 22 22:17:21 2015
EOFIPTABLES
#
echo "MANUALLY edit /etc/iptables/iptables.rules, and replace source ip-of-server by real IP-address of server"
# get IP address of RPI
# 1 is shorthand for 1.0.0.0): no spaces around '=' character
IPnr=`ip route get 1 | awk '{print $NF;exit}'`
echo "IP address of server running this script is: " $IPnr
read -n1 -r -p "Press space if IP-address is adapted..." key
#
systemctl enable iptables
systemctl start iptables

